src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="post", orphanRemoval=true)
     * @ORM\OrderBy({"created_at" = "DESC"})
     */
    private $comments;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->comments = new ArrayCollection();
    }

    public function get(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }


    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = ucfirst($first_name);

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = ucfirst($last_name);

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getFullName(): string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\Post;
use App\Entity\Comment;

class PostController extends AbstractController
{
    public const LIMIT_POSTS_BLOCK = 5;
    public const POSTS_PER_PAGE = 8;
    public const COMMENTS_PER_PAGE = 8;

    /**
     * @Route("/", name="homepage")
     */
    public function index(): Response
    {
        $postRepository = $this->getDoctrine()->getRepository(Post::class);

        $newestPosts = $postRepository
            ->findBy(
                [],
                ['created_at' => 'DESC'],
                self::LIMIT_POSTS_BLOCK
            );

        $popularPosts = $postRepository->findByMoreCommentsCount(self::LIMIT_POSTS_BLOCK);

        return $this->render('post/index.html.twig', [
            'newest_posts' => $newestPosts,
            'popular_posts' => $popularPosts,
        ]);
    }

    /**
     * @Route("/post/all", name="post_all")
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function showAll(Request $request, PaginatorInterface $paginator): Response
    {
        $allPosts = $this->getDoctrine()->getRepository(Post::class)->findBy(
            [],
            ['created_at' => 'DESC']
        );

        $posts = $paginator->paginate(
            $allPosts,
            $request->query->getInt('page', 1),
            self::POSTS_PER_PAGE
        );

        return $this->render('post/all.html.twig', [
            'posts' => $posts
        ]);
    }

    /**
     * @Route("/post/{id}", name="post_view")
     * @param $id
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function view($id, Request $request, PaginatorInterface $paginator): Response
    {
        $post = $this->getDoctrine()->getRepository(Post::class)->find($id);

        $comments = $paginator->paginate(
            $post->getComments(),
            $request->query->getInt('page', 1),
            self::COMMENTS_PER_PAGE
        );

        return $this->render('post/view.html.twig', [
            'post' => $post,
            'comments' => $comments
        ]);
    }
}

templates/post/all.html.twig
{% extends 'base.html.twig' %}

{% block title %}Symfony Blog{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/paginator.css') }}" type="text/css" rel="stylesheet" />
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <h2>Posts</h2>

                <div class="container">
                    <ul class="list-group">
                        {% for post in posts %}
                            <li class="list-group-item clearfix">
                                {{ include('post/item.html.twig', {post: post}) }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="container">
                    {{ include('pagination.html.twig', {pagination: posts}) }}
                </div>

            </div>
            <div class="col-sm-1"></div>
        </div>
    </div>
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Symfony Blog{% endblock %}

{% block to_all_posts %}
    <h2 class="all-posts-link"><a href="{{ path('post_all') }}">All posts</a></h2>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h2>Newest posts</h2>
                <div class="container">
                    <ul class="list-group">
                        {% for post in newest_posts %}
                            <li class="list-group-item clearfix">
                                {{ include('post/item.html.twig', {post: post}) }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-sm-6">
                <h2>Popular posts</h2>
                <div class="container">
                    <ul class="list-group">
                        {% for post in popular_posts %}
                            <li class="list-group-item clearfix">
                                {{ include('post/item.html.twig', {post: post}) }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/post/item.html.twig
<h3 class="list-group-item-heading">{{ post.title }}</span></h3>
{% if post.user is defined %}
    <p class="text-muted">Author: {{ post.user.fullName }}, created {{ post.createdAt|date('d/m/Y') }}</p>
{% else %}
    <p class="text-muted">Author: {{ post.user_first_name }} {{ post.user_last_name }}, created {{ post.created_at|date('d/m/Y') }}</p>
{% endif %}
<div class="list-group-item-text lead">
    {{ post.description|raw }}
    <div><a href="{{ path('post_view', {id: post.id}) }}"><small>Read more&#8230;</small></a></div>
</div>

templates/post/view.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/paginator.css') }}" type="text/css" rel="stylesheet" />
{% endblock %}

{% block body %}
    <div class="container">

        <div class="row">
            <div class="col-sm-12">
                <h2>{{ post.title }}</h2>
                <div class="list-group list-group-item">
                    <div class="details">
                        <p class="text-info">Author: {{ post.user.fullName }}</p>
                        <p class="text-info">Created: {{ post.createdAt|date('d/m/Y') }}</p>
                        <p class="text-muted list-group-item-text">{{ post.description|raw }}</p>
                    </div>
                    <div>{{ post.body|raw }}</div>
                </div>
            </div>
        </div>
        <br/>

        {% if app.user and is_granted('ROLE_USER') %}
            <div class="row">
                <div class="col-sm-12">
                    {{ render(controller('App\\Controller\\CommentController::add', {'postId': post.id})) }}
                </div>
            </div>
            <br/>
        {% else %}
            <div class="row">
            <div class="col-sm-12">
            <div class="list-group list-group-item">
            <div class="details">
                <p>You have to be authorized to put comment here</p>
            </div>
            </div>
            </div>
            </div>
            <br/>
        {% endif %}

        <div class="row">
            <div class="col-sm-12">
                {{ include('post/comment/list.html.twig', {comments: comments}) }}
            </div>
        </div>

    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/jquery-3.5.1.min.js') }}" type="text/javascript"></script>

    <script>
        $(".comment-block").on("click", ".edit-link", function (e) {
            var commentId = $(this).attr("data-id");
            e.preventDefault();
            var $link = $(e.currentTarget);
            $.ajax({
                method: "POST",
                data: {
                    "commentId": commentId
                },
                url: $link.attr("href")
            }).done(function(data){
                $("#comment-block-" + commentId + " .text-block").html(data.output);
            });
        });
    </script>
{% endblock %}